# Generated by Django 2.0.7 on 2018-08-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_type', models.CharField(choices=[('Flat', 'Flat'), ('House', 'House'), ('Apartment', 'Apartment')], default='House', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('album', models.TextField()),
                ('desc', models.CharField(max_length=100)),
                ('adv_desc', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('avaliable', models.DurationField()),
                ('price_per_day', models.PositiveIntegerField()),
                ('guest_num', models.PositiveIntegerField(default=1)),
                ('bedroom_num', models.PositiveIntegerField(default=0)),
                ('bed_num', models.PositiveIntegerField(default=0)),
                ('bathroom_num', models.PositiveIntegerField(default=0)),
                ('wifi', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('other_facilities', models.TextField()),
                ('cancellation', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], default='R1', max_length=10)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Host')),
            ],
        ),
    ]
